services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
       db:
          condition: service_healthy
  db:
    image: mysql
      #   volumes:
    #     - ./tmp/db:/var/lib/mysql/data
    environment:
      #      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      #MYSQL_DATABASE: fahrradverleih
      MYSQL_USER: max
      MYSQL_PASSWORD: blabla
    ports:
      - "3303:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    #   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #   interval: 1s