services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
       - db
    #     condition: service_healthy
  db:
    image: mysql
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: quickstart_db
      MYSQL_USER: max
      MYSQL_PASSWORD: blabla
    ports:
      - "3303:3306"
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #   interval: 1s