-- CREATE USER 'max'@'172.17.0.1' IDENTIFIED BY 'blabla';
GRANT ALL PRIVILEGES ON *.* TO 'max'@'172.0.0.1' WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.0.0.1' WITH GRANT OPTION;
flush privileges;
DROP SCHEMA IF EXISTS fahrradverleih;
CREATE SCHEMA IF NOT EXISTS `fahrradverleih`;
DROP SCHEMA IF EXISTS mondial;
CREATE SCHEMA IF NOT EXISTS `mondial`;
